[package]
name = "slant-launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termsize = "0.1"
colored = "2"
console = "0.15.0"
rand = "0.8.5"
